### ISSUE TITLE
Bugs in Production

### ISSUE THREAD

**Issue by AdamW19** [ucsdeventhub/EventHub#41]
Here's a list of all the bugs I found in prod so far. I'll update as I find new ones. Check off the bug when it's been fixed:

- [x] 1. Loginning in as `test-org@ucsd.edu` results in a 500 Internal Server error:
<img width="750" alt="Screen Shot 2020-12-06 at 11 21 39 PM" src="https://user-images.githubusercontent.com/13486520/101321175-cd061d80-3819-11eb-96fa-b13b42283140.png">

Issue also occurs with other emails:
<img width="755" alt="Screen Shot 2020-12-06 at 11 52 44 PM" src="https://user-images.githubusercontent.com/13486520/101323843-25d7b500-381e-11eb-8a13-ce49f119bd7b.png">

- [x] 2. Visiting the website results in an uncaught exception when not logged in:
<img width="749" alt="Screen Shot 2020-12-06 at 11 22 44 PM" src="https://user-images.githubusercontent.com/13486520/101321260-f2932700-3819-11eb-8aa2-fd34ca5dc355.png">

- [x] 3. Searching by `before:2020-12-30` results in an uncaught exception (due to the regex not allowing `-`):
<img width="748" alt="Screen Shot 2020-12-06 at 11 24 07 PM" src="https://user-images.githubusercontent.com/13486520/101321401-24a48900-381a-11eb-9684-7afa8dc1018e.png">

**Comment by AdamW19** [comment]
Bug #2 appears to be fixed from running the latest version of `main`.

I'm waiting for verification from others but for now I'm gonna check this off.

**Comment by AdamW19** [comment]
[PR #46](https://github.com/ucsdeventhub/EventHub/pull/46) fixes number 3 and a majority of the warnings from `node`.

Let me know if you need help w/ number 1 Julio.

**Comment by ear7h** [comment]
1 has been fixed, it was a deployment issue. The database file was owned by root and the server itself runs on a lower privileged user so sqlite was automatically treating the database as read-only. The database file is now owned by the user that runs the api job
